[package]
name = "sbol"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sophia = "0.7.2"
xml-rs = "0.8.4"
serde = "1.0.156"
url = "2.3.1"
uuid = "1.3.0"
regex = "1.7.1"
